modLoader="javafml"
loaderVersion="[1,)"
issueTrackerURL="https://github.com/owmii/powah/issues"
license="LGPLv3"

[[mods]]
modId="powah"
version="0.0.0"
displayName="Powah"
displayURL="https://www.curseforge.com/minecraft/mc-mods/powah"
authors="owmii,Technici4n,shartte"
description='''
Various ways to generate, store and transmit FE power.
'''

[[dependencies.powah]]
    modId="neoforge"
    type="REQUIRED"
    versionRange="[21.1.1,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.powah]]
    modId="cloth_config"
    type="REQUIRED"
    versionRange="*"
    ordering="NONE"
    side="BOTH"

[[dependencies.powah]]
    modId="jei"
    type="OPTIONAL"
    versionRange="[19.18.3,)"
    ordering="NONE"
    side="CLIENT"
